version: '3.8'

services:
  cifar-dev:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # Mapea el proyecto completo
      - ..:/workspaces:cached

      # Mapea específicamente la carpeta data y los modelos para persistencia explícita
      - ../data:/app/data
      - ../mejor_modelo.pth:/app/mejor_modelo.pth
      - ../mejor_modelo_mlp.pth:/app/mejor_modelo_mlp.pth

    command: sleep infinity

    # Opcional: habilita depuradores basados en ptrace
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
